services:
  - type: web
    name: leetcode-stalker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_DEFAULT_CHAT_ID
        sync: false
      - key: POLL_INTERVAL_SECONDS
        value: "60"
      - key: ENABLE_TELEGRAM_POLLING
        value: "true"
